name: Pytest
run-name: Push to ${{ github.ref_name }} by @${{ github.actor }}
on: 
    push:
        branches:
            - main
            - develop

jobs:
    Pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Dump context
              uses: crazy-max/ghaction-dump-context@v2.1.0

            - name: Setup Python
              uses: actions/setup-python@v5.0.0
              with:
                python-version: '3.11'

            - name: Install Python Requirements
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip check
