name: Pytest
run-name: ${{github.event_name}} to ${{ github.ref_name }} by @${{ github.actor }}
on: 
    push:
      branches:
        - develop

    pull_request:
      branches:
        - main

    schedule:
      - cron: '0 */1 * * *'

jobs:
    Soda-Core:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5.0.0
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip check
        
        - name: Soda Test Connection
          env:
            POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
            POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          run: |
            soda test-connection -d render_postgres -c .soda/configuration.yml
            soda scan -d render_postgres -c .soda/configuration.yml .soda/checks.yml

        - name: Soda Library Action
          uses: sodadata/soda-github-action@v1.0.2
          env:
            POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
            POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          with:
            soda_library_version: latest
            data_source: render_postgres
            configuration: .soda/configuration.yaml
            checks: .soda/checks.yaml
