name: Pytest
run-name: Push to ${{ github.ref_name }} by @${{ github.actor }}
on: 
    push:
        branches:
            - main
            - develop

jobs:
    Pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5.0.0
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip check
            
            - name: Install Soda Postgres
              run: |
                pip install -i https://pypi.cloud.soda.io soda-postgres

            - name: Soda Test Connection
              env:
                POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
                POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
                POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
              run: |
                soda test-connection -d render_postgres -c .soda/configuration.yml
